a

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,6 +27,10 @@ jobs:
         id: get_tag
         run: |
           TAG_NAME=$(cat RELEASE.md|  grep -oP 'v\d+\.\d+\.\d+' | head -n 1)
+          if [ "$TAG_NAME" == "" ]; then
+            echo "Could not read tag from RELEASE.md"
+            exit 1
+          fi
           response_code=$(curl -s -o /dev/null -w "%{http_code}" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/${{ github.repository }}/git/refs/tags/$TAG_NAME)
           if [ "$response_code" = "200" ]; then
             echo "Tag $TAG_NAME already exists."
